# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e71879305d85fbe557dd001ca9c24d7a5ed089886d1eaabc1928f06eeed1b095063e415e825d4118532053f96544b9acea81b268a4a8ebc8634f6e752ef42c0

test:
  secret_key_base: c9246712322b9cc1b3240af31c0308f77865049b422df697cf4519812cd85be709f51b679b4df9afaa413c3cac8211091509c412666cd4237627abce0aea02aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
